# Generated by Django 2.0.13 on 2019-05-25 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primeiro_Migrate_SQN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste_titulo', models.CharField(max_length=200)),
                ('teste_texto', models.TextField()),
                ('teste_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('teste_date2', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
