# Generated by Django 2.0.13 on 2019-05-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_primeiro_migrate_sqn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primeiro_Migrate_SQN',
            new_name='Primeiro_Migrate_SQN2',
        ),
    ]
