sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=forcelinerobot
    - REGISTRY_PASS="789456qwe"

script:
  - docker build --tag forceline/forceline .
  - docker run forceline/forceline

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push gsoares01/forceline
  on:
    branch: test_docker
