language: node_js
node_js:
  - "2.7"

#dependencias 
install:
  - npm install -g selenium-webdriver
#env:
# - [
#      {secure: "6eda8b70d763de6dea5a011390462930"},
#      {secure: "5ed2e5e70113b7fc784d3f4d96306b96"}
#    ]
#DEBUG=True
#DATABASE_URL="mysql://localhost/test"

#before_script é um campo que informa tudo que deve ser executado antes do Travis testar nosso “deploy”
#before_script:
#- psql -c 'create database test;' -U mysql

#run test

script:
  - travis encrypt username/projectname TESTINGBOT_KEY=TESTINGBOT_KEY
  - travis encrypt username/projectname TESTINGBOT_SECRET=TESTINGBOT_SECRET
  - node tests/site/*.js

#script: nosetests my_unittests.py
git:
  depth: 250
  depth: false


#script: python app.py

on:
  branch: master

notifications:
  slack:
    rooms:
      - forcelineworkspace:ssVn0EAS5yVyvSyiv4Tph7n3#travis

deploy:
    provider: heroku
    api_key: 
      secure: "113ecc07-711e-4211-891e-6107c540a438"
