sudo: required
services:
  - docker
addons:
  ssh_known_hosts: 167.99.144.191
script:
  - docker build -t forcelineproject:latest .

after_script:
  - docker images
  - docker run -d --name forceline --restart=always -p 8000:8000 forcelineproject:latest
