sudo: required	
services:	
  - docker	
addons:	
  ssh_known_hosts: 206.81.8.182

branch:	
  only:	
  - test_docker	

script:	
  - docker build -t forcelineproject:latest .
  - docker run -d --name forceline --restart=always -p 8000:8000 forcelineproject:latest

deploy:
  provider: script
  script:
    - chmod 600 deploy_key
    - mv deploy_key ~/.ssh/id_rsa
    - ssh -i ./deploy_key root@206.81.8.182 "cd /project/ForceLineProject; ./circle_deployer.sh"
  on:
    branch: test_docker