language: python
node:
- '3.7'
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
dist: trusty
addons:
  sonarcloud:
    organization: lucasdlg5-github
    token:
      secure: 6fd1c5449b5a0c11a121eaf42761bb56af0b118b
branch:
  only:
  - master

script:
- sonar-scanner

before_install:
  - pip install fabric3
  - openssl aes-256-cbc -salt -a -d -in deploy_key_enc -out deploy_key -k 123
  - fab docker_deployer