language: python
node:
- '3.7'
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
dist: trusty
addons:
  sonarcloud:
    organization: lucasdlg5-github
    token:
      secure: 6fd1c5449b5a0c11a121eaf42761bb56af0b118b
branch:
  only:
  - master

script:
- sonar-scanner

before_install:
  - openssl enc -aes-256-cbc -d -in deploy_key.enc -out deploy_key -k 12345
  - cat deploy_key
  #- ls -la
  #- ssh -i ./id_rsa.pub root@206.81.8.182 "cd /project/ForceLineProject; sudo bash ./bash_deployer.sh"
  #- sudo apt-get install sshpass
  #- bash ssh_script_conn.bash
  #- cd /project/ForceLineProject
  #- bash ./bash_deployer.sh
  #- sudo apt-get install google-chrome-stable
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://206.81.8.182:8000

before_script:
- ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
