sudo: required	
services:	
  - docker	
addons:	
  ssh_known_hosts: 206.81.8.182

branch:	
  only:	
  - master	

script:	
  - docker build -t forcelineproject:latest .

before_install:
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
  - ssh -i ./deploy_key root@206.81.8.182 "cd /project/ForceLineProject; sudo bash ./circle_deployer.sh"