language: python:
  "3.6"
  branch: master
  - "pypy"

install:
  - pip install .
  - pip install requirements.txt

notifications:  
  slack:
    rooms:
    - forcelineworkspace:ssVn0EAS5yVyvSyiv4Tph7n3#travis
    