language: python
node:
  - "3.7"

install:
  - pip install -r requirements.txt

sudo: required	
services:	
  - docker	
dist: trusty
addons:	
  ssh_known_hosts: 206.81.8.182
  chrome: stable

branch:	
  only:	
  - master

script:
  - docker build -t forcelineproject:latest .
  - nosetests -v --with-coverage --cover-tests --cover-package=tests tests/test_app.py
  
before_install:
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
  - ssh -i ./deploy_key root@206.81.8.182 "cd /project/ForceLineProject; sudo bash ./circle_deployer.sh"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://206.81.8.182:8000 &
