language: python
python:
- '3.6'
sudo: true
script:
- pip install pyopenssl ndg-httpsclient pyasn1
- pip install -r requirements.txt
true:
  branch: master
notifications:
  slack:
    rooms:
    - forcelineworkspace:ssVn0EAS5yVyvSyiv4Tph7n3#travis
deploy:
  provider: heroku
  api_key:
    secure: GcxGPATUDAMd9FAUZUwoMVSD0Aj7yrmGQnzPefN8CKdiK0jchzln6lkrTOD6QyOJ36Pj/4zSNAIcLBYlbZMjmiQjldQ3dtSDdnn1rjzCucRMWebtW09Mgpy6/Dd2ssOBaVKpRXRqPEdbPwRB7lLfgDto1VZmC5tQEa7rKB/+QlqPYqyWqrydL9owYcJOlc7AVHwUHLapy508xv27tCab2anjpzm0s1Ruq3U1wffnM8UVKxYHiTQzmFcGGXcQbsGacjDAzBppmBolcwyd2wmCfjIgS5IrA1/ibyA1B3qsAkTPVxgHZuMEqvH/2+vX9R9i3EZztV0ecPAVC4wmzXkvisWy9VrABTqGuaEezxRIhso0NviF7waxip28XCWbK+F8cbk2urxUHjJT8ez+Ys/uV69I0dGmqhNxt2tsi9XZSmyjj7Lv4q2DkUK/VMiIAgINAzQU/OWpwXiVUJr+oQvjM9RJmxOD2v2p/1FFecGuvDECSnXwSQwVeQ62AF65rX7yyDQh+/KbAOtbkb/zk9UU/sgnx9RFg5lij+lO3TLhTOHujccHwPxjUmj4tvVkdAGr+DzfoIEYxu9URvCpDaW7KFEUXkyatNEm2aivx9r58nKWhOH8yfO9AWSyf+H1caJUupOxLXtNvsaCNd7dRdk6lmONib1x7LYf6OZEfSYrLas=
  app: forcelineworkspace
  on:
    repo: lucasdlg5/ForceLineProject
