language: python
python:
  - "3.6"

sudo: true 

script:
  - pip install pyopenssl ndg-httpsclient pyasn1
  - pip install -r requirements.txt
  
after_script:
  - python app.py
on:
  branch: master

notifications:  
  slack:
    rooms:
    - forcelineworkspace:ssVn0EAS5yVyvSyiv4Tph7n3#travis
    