language: python
node:
- '3.7'
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
dist: trusty
addons:
  sonarcloud:
    organization: lucasdlg5-github
    token:
      secure: 6fd1c5449b5a0c11a121eaf42761bb56af0b118b
branch:
  only:
  - master

script:
- sonar-scanner

before_install:
- openssl aes-256-cbc -K $encrypted_0eaab3035508_key -iv $encrypted_0eaab3035508_iv
  -in id_rsa.pub.enc -out .\\id_rsa.pub -d
- sudo apt-get install google-chrome-stable
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://206.81.8.182:8000

before_script:
- ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
