sudo: required	
services:	
  - docker	
addons:	
  ssh_known_hosts: 206.81.8.182

branch:	
  only:	
  - test_docker	

script:	
  - docker build -t forcelineproject:latest .	

before_install:
  - ssh -i ./deploy_key root@206.81.8.182 pwd