machine:
  services:
    - docker
dependencies:
  pre:
    - docker info
  override:
    - docker build -t forceline:latest .
deployment:
  master:
    branch: test_docker
    commands:
      - echo 'Deploying'
      - ssh -v root@$206.81.8.182 "cd /project/ForceLineProject; ./circle_deployer.sh"